ALTER TABLE devices ADD COLUMN user_name TEXT NOT NULL DEFAULT '未设置';
ALTER TABLE devices ADD COLUMN target_category INTEGER NOT NULL DEFAULT 0;
ALTER TABLE devices ADD COLUMN connection_protocol INTEGER NOT NULL DEFAULT 0;
